In [1]:
import torch

In [18]:
ids, activations = torch.load('/workspace/llm-progress-monitor/rollouts-test/activations/0.pt')

In [19]:
ids.shape

torch.Size([32])

In [20]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
tokenizer.decode(ids)

'<bos><start_of_turn>user\nWrite a short story about a cat and a dog.<end_of_turn>\n<start_of_turn>model\nJasper, a sleek black cat with ice-blue<end_of_turn>\n'

In [13]:
activations.shape

torch.Size([26, 33, 2304])

In [6]:
ids

tensor([     2,      2,    106,   1645,    108,   5559,    476,   3309,   3904,
          1105,    476,   4401,    578,    476,   5929, 235265,    107,    108,
           106,   2516,    108, 123635, 235269,    476,  69392,   2656,   4401,
           675,   8357, 235290,   8796,    107,    108])

In [1]:
import torch

In [5]:
torch.load('/workspace/llm-progress-monitor/rollouts-test/activations/0.pt')

(tensor([151644,    872,    198,   7985,    264,   2805,   3364,    911,    264,
           8251,    323,    264,   5562,     13, 151645,    198, 151644,  77091,
            198, 151667,    271, 151668,    271,    641,    264,  11340,   2632,
           6290,  88677,   1948,  20097,  34131,    323,    264,  34855,    287,
          13638,     11,   1052,  12163,    264,   8251,   6941,  57400,    323,
            264,   5562,   6941,   7487,     13,   2379,   1033,  18709,     11,
           5382,    304,    279,   1852,   2613,  45622,     11,   3498,    807,
           2581,   9428,   2270,     13,  57400,     11,    448,   1059,  47394,
           3691,  18241,    323,  20748,   6414,     11,  14915,    311,  25859,
            304,    279,   7015,  53871,    429,  18293,   1526,    279,  11030,
             13,   7487,     11,    264,  20748,  10759,    423,    448,    264,
          11657,  15289,     11,    572,   2677,    700,  23966,    279,  32533,
            323,    279,   5

In [4]:
torch.load('/workspace/llm-progress-monitor/rollouts-test/activations/1.pt')[1]

tensor([[[-7.8400e+02,  4.9688e+00, -2.5125e+01,  ...,  7.1875e-01,
           5.0938e+00,  1.6953e+00],
         [ 3.5000e+01,  4.0625e+00, -7.2500e+00,  ..., -1.3086e-01,
           2.1387e-01,  1.8262e-01],
         [ 3.2250e+01,  3.8125e+00, -4.1250e+00,  ..., -7.4609e-01,
          -1.9727e-01,  1.0645e-01],
         ...,
         [ 2.0250e+01,  3.2500e+00,  3.0312e+00,  ..., -2.3242e-01,
           4.5508e-01, -5.2734e-02],
         [ 1.5875e+01,  3.3594e+00,  1.5625e+00,  ...,  8.4961e-02,
           9.7656e-02, -8.0078e-02],
         [ 1.7875e+01,  4.1875e+00,  1.4609e+00,  ..., -1.9531e-03,
           3.5938e-01, -3.9062e-02]]], dtype=torch.bfloat16)